### PR TITLE
Migrate to androidX

### PR DESCRIPTION
**Pull request by rinav**
This pull request consist
- Migrate to androidX
- Bump Kotlin version
- Bump Gradle version
- Upgrade project to use kotlin-stdlib-jdk8 instead of jre7

### CODE REVIEW

**Comment by rinav** [comment]
Can we merge this PR?

**Comment by poovamraj** [comment]
Merged it to master. Thanks for the PR @rinav

**Comment by rinav** [comment]
Will you release a new version or wait for more fixes?

**Comment by poovamraj** [comment]
implementation 'com.poovam:pin-edittext-field:1.2.2'

You can use this build

**Pull request merged**
